spring:
  application:
    name: gallery-service
  data:
    mongodb:
      uri: mongodb://localhost:27018/gallerydb
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

---